# Generated by Django 5.1.2 on 2024-11-16 05:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('specification', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('current_price', models.FloatField()),
                ('discount_type', models.CharField(blank=True, max_length=100, null=True)),
                ('store', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_usage_days', models.IntegerField()),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_cost', models.FloatField()),
                ('expense_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_expenses', to='records.expenserecord')),
            ],
        ),
    ]
