# Generated by Django 5.1.2 on 2024-11-16 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='actual_usage_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='daily_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='expense_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_expenses', to='records.expenserecord'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incomerecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
