# Generated by Django 5.1.2 on 2024-11-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_expenserecord_user_alter_incomerecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='currency',
            field=models.CharField(choices=[('GBP', '英镑 (GBP)'), ('CNY', '人民币 (CNY)'), ('TWD', '新台币 (TWD)'), ('USD', '美元 (USD)'), ('EUR', '欧元 (EUR)'), ('JPY', '日元 (JPY)'), ('AUD', '澳元 (AUD)'), ('CAD', '加元 (CAD)'), ('HKD', '港币 (HKD)')], default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='currency',
            field=models.CharField(choices=[('GBP', '英镑 (GBP)'), ('CNY', '人民币 (CNY)'), ('TWD', '新台币 (TWD)'), ('USD', '美元 (USD)'), ('EUR', '欧元 (EUR)'), ('JPY', '日元 (JPY)'), ('AUD', '澳元 (AUD)'), ('CAD', '加元 (CAD)'), ('HKD', '港币 (HKD)')], default='GBP', max_length=3),
        ),
    ]
