# Generated by Django 5.1.2 on 2024-11-16 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_expenserecord_currency_incomerecord_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomerecord',
            name='ddl',
            field=models.DateField(default=datetime.datetime(2024, 11, 16, 7, 40, 51, 576498, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='expected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='status',
            field=models.CharField(choices=[('pending', '未完成'), ('unpaid', '未支付'), ('completed', '已完成')], default='pending', max_length=20),
        ),
    ]
