# Generated by Django 5.1.2 on 2024-11-16 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_incomerecord_ddl_incomerecord_expected_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomerecord',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incomerecord',
            name='ddl',
            field=models.DateField(default=datetime.datetime(2024, 11, 16, 7, 47, 14, 975732, tzinfo=datetime.timezone.utc)),
        ),
    ]
