# Generated by Django 4.2.18 on 2025-03-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=5),
        ),
    ]
