# Generated by Django 4.2.18 on 2025-03-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_category_alter_transaction_category'),
    ]

    operations = [
    ]
