# Generated by Django 4.2.18 on 2025-03-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_alter_account_account_type_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='icons/default.svg', max_length=255),
        ),
    ]
